[build]
command = "npm run build"
publish = "dist"
image = "ubuntu-22.04" # Use a build image with Playwright dependencies included

[build.environment]
NODE_VERSION = "20"

[functions]
node_bundler = "esbuild"
